on: [push, pull_request]
name: Test
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install build dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y \
          build-essential \
          libvips \
          libvips-dev \
          vips
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: stable
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build
      run: |
        go build ./...
